# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np

# Create a student data frame
data = {
    'student_id': [1, 2, 3, 4, 5],
    'name': ['Reema', 'Nada', 'Ghada', 'Maram', 'Leena'],
    'level': ['Undergraduate', 'Graduate', 'Undergraduate', 'Undergraduate', 'Graduate'],
    'student_DoB': ['2003-05-15', '2000-11-20', '2004-01-10', '2003-07-01', '1999-09-25']
}
student_df = pd.DataFrame(data)

# Add a column name "student_GPA" with random GPA out of 5
student_df['student_GPA'] = np.random.uniform(1.0, 5.0, size=len(student_df)).round(2)

# Display the complete data frame
print("Student DataFrame:")
display(student_df)

# Display the summary of the data frame
df.info()