# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

from google.colab import drive  # Import the Colab library that allows interaction with Google Drive
drive.mount('/content/drive')


df=pd.read_csv('/content/drive/MyDrive/tiktok_google_play_reviews.csv') #reads the CSV file from Drive into a DataFrame.

# the first 10 records.
df.head(10)

#summary of the dataset
df.describe()

df.info()

# Print out the content (review) and score for user (md roni)
md_roni_reviews = df[df['userName'] == 'md roni']
md_roni_reviews[['content', 'score']]