# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import numpy as np


vector1 = np.array([1, 3, 4, 5, 10, 11, 12, 13, 14])
vector2 = np.array([15, 1, 3, 4, 5, 10, 11, 12, 13])


m1 = vector1.reshape(3,3)
m2 = vector2.reshape(3,3)

#  Array
result = np.array([m1, m2])

print("Matrix 1:\n", m1)
print("Matrix 2:\n", m2)


print("Second row of 2nd matrix:", result[1][1])


print("Third column of 1st matrix:", result[0][:,2])
